title: 'All about Infosec from Omerta.nl  '
purpose: []
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
color:
  saturation: 0.5573476
  brandStrength: 0.25
  lightness: 0.2956989
  brandColors:
    - '#7f7f7f'
    - '#000000'
    - '#2c2c2c'
    - '#555555'
    - '#dbd5c5'
  rhythmicContrast: 1
cta:
  bucket: null
  version: null
  domain: null
analytics:
  twitter: null
  google: null
  facebook: null
favicon: null
name: Omerta Information Security
opengraph:
  image: null
  type: null
  appId: null
typography_spectrum: 0.3733572
layout_spectrum: 0.1403823
