name: Omerta Information Security
favicon: null
layout_spectrum: 0.3822547267191112
typography_spectrum: 0.9977222031448036
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#FF6700'
    - '#EBEBEB'
    - '#C0C0C0'
    - '#3A6EA5'
    - '#004E98'
  brandStrength: 0.2829918824136257
  lightness: 0.3453641978558153
  saturation: 0.6991618792526424
  rhythmicContrast: 0.8052211916074157
purpose: []
