name: Omerta Information Security
favicon: null
layout_spectrum: 0.99996
typography_spectrum: 0.23432
title: 'All about Infosec from Rotterdam, The Netherlands'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#7f7f7f'
    - '#000000'
    - '#2c2c2c'
    - '#555555'
    - '#dbd5c5'
  brandStrength: 0.25
  lightness: 0.6875
  saturation: 0.5
  rhythmicContrast: 0.75
purpose: []
