name: Omerta Information Security
favicon: null
layout_spectrum: 0.3377
typography_spectrum: 0.9977222031448036
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#7f7f7f'
    - '#000000'
    - '#2c2c2c'
    - '#555555'
    - '#dbd5c5'
  brandStrength: 0.25
  lightness: 0.4375
  saturation: 0.75
  rhythmicContrast: 0.8052211916074157
purpose: []
